//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Honeywell.GWS.Connector.Library.Workflows.Picking.Rest.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Honeywell.GWS.Connector.Library.Workflows.Picking.Rest.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An error occurred.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error registering break start &apos;{0}&apos;: {1}.
        /// </summary>
        internal static string Error_BeginBreak {
            get {
                return ResourceManager.GetString("Error_BeginBreak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error accessing: {0}.
        /// </summary>
        internal static string Error_Connect {
            get {
                return ResourceManager.GetString("Error_Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error accessing: no response received from the server.
        /// </summary>
        internal static string Error_ConnectMissingServerResponse {
            get {
                return ResourceManager.GetString("Error_ConnectMissingServerResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error to disconnect: {0}.
        /// </summary>
        internal static string Error_Disconnect {
            get {
                return ResourceManager.GetString("Error_Disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error registering break end: {0}.
        /// </summary>
        internal static string Error_EndBreak {
            get {
                return ResourceManager.GetString("Error_EndBreak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error printing label batch &apos;{0}&apos;: {1}.
        /// </summary>
        internal static string Error_PrintLabels {
            get {
                return ResourceManager.GetString("Error_PrintLabels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error registering start: {0}.
        /// </summary>
        internal static string Error_RegisterOperator {
            get {
                return ResourceManager.GetString("Error_RegisterOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No response from server.
        /// </summary>
        internal static string Error_ServerResponse {
            get {
                return ResourceManager.GetString("Error_ServerResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error registering task &apos;{0}&apos;: {1}.
        /// </summary>
        internal static string Error_SetWork {
            get {
                return ResourceManager.GetString("Error_SetWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unknown reason.
        /// </summary>
        internal static string Error_UnknownReason {
            get {
                return ResourceManager.GetString("Error_UnknownReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid response from server.
        /// </summary>
        internal static string InvalidResponse {
            get {
                return ResourceManager.GetString("InvalidResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid response content.
        /// </summary>
        internal static string InvalidResponseContent {
            get {
                return ResourceManager.GetString("InvalidResponseContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Server is mandatory.
        /// </summary>
        internal static string ServerEmpty {
            get {
                return ResourceManager.GetString("ServerEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User {0} not found.
        /// </summary>
        internal static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
    }
}
