//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Honeywell.GWS.Connector.Library.Workflows.Checklist.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DialogResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DialogResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Honeywell.GWS.Connector.Library.Workflows.Checklist.Properties.DialogResources", typeof(DialogResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        public static string Date_Day {
            get {
                return ResourceManager.GetString("Date_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day repeated.
        /// </summary>
        public static string Date_DayRepeated {
            get {
                return ResourceManager.GetString("Date_DayRepeated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contains invalid characters (only &apos;d&apos;, &apos;M&apos; and &apos;y&apos; are allowed).
        /// </summary>
        public static string Date_InvalidCharacters {
            get {
                return ResourceManager.GetString("Date_InvalidCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid date.
        /// </summary>
        public static string Date_InvalidDate {
            get {
                return ResourceManager.GetString("Date_InvalidDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        public static string Date_Month {
            get {
                return ResourceManager.GetString("Date_Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month repeated.
        /// </summary>
        public static string Date_MonthRepeated {
            get {
                return ResourceManager.GetString("Date_MonthRepeated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does not contains any matches (only &apos;dd&apos;, &apos;MM&apos;, &apos;yyyy&apos; and &apos;yy&apos; are allowed).
        /// </summary>
        public static string Date_NoMatches {
            get {
                return ResourceManager.GetString("Date_NoMatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string Date_Year {
            get {
                return ResourceManager.GetString("Date_Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year repeated.
        /// </summary>
        public static string Date_YearRepeated {
            get {
                return ResourceManager.GetString("Date_YearRepeated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Four digits.
        /// </summary>
        public static string FourDigits {
            get {
                return ResourceManager.GetString("FourDigits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, to continue say VCONFIRM.
        /// </summary>
        public static string Message_ToContinueSayVCONFIRM {
            get {
                return ResourceManager.GetString("Message_ToContinueSayVCONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing device state.
        /// </summary>
        public static string MissingDeviceState {
            get {
                return ResourceManager.GetString("MissingDeviceState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing required variable &apos;{0}&apos;.
        /// </summary>
        public static string MissingRequiredVariable {
            get {
                return ResourceManager.GetString("MissingRequiredVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A valid value for option &apos;{0}&apos; is missing. Initialized with value &apos;{1}&apos;.
        /// </summary>
        public static string Options_InvalidValue {
            get {
                return ResourceManager.GetString("Options_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong.
        /// </summary>
        public static string Select_Wrong {
            get {
                return ResourceManager.GetString("Select_Wrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string SelectMultiple_Next {
            get {
                return ResourceManager.GetString("SelectMultiple_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator not found.
        /// </summary>
        public static string ServerConnection_OperatorNotFound_Voice {
            get {
                return ResourceManager.GetString("ServerConnection_OperatorNotFound_Voice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hour.
        /// </summary>
        public static string Time_Hour {
            get {
                return ResourceManager.GetString("Time_Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hour repeated.
        /// </summary>
        public static string Time_HourRepeated {
            get {
                return ResourceManager.GetString("Time_HourRepeated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contains invalid characters (only &apos;h&apos;, &apos;m&apos; and &apos;s&apos; are allowed).
        /// </summary>
        public static string Time_InvalidCharacters {
            get {
                return ResourceManager.GetString("Time_InvalidCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minute.
        /// </summary>
        public static string Time_Minute {
            get {
                return ResourceManager.GetString("Time_Minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minute repeated.
        /// </summary>
        public static string Time_MinuteRepeated {
            get {
                return ResourceManager.GetString("Time_MinuteRepeated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does not contains any matches (only &apos;hh&apos;, &apos;mm&apos; and &apos;ss&apos; are allowed).
        /// </summary>
        public static string Time_NoMatches {
            get {
                return ResourceManager.GetString("Time_NoMatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second.
        /// </summary>
        public static string Time_Second {
            get {
                return ResourceManager.GetString("Time_Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second repeated.
        /// </summary>
        public static string Time_SecondRepeated {
            get {
                return ResourceManager.GetString("Time_SecondRepeated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two digits.
        /// </summary>
        public static string TwoDigits {
            get {
                return ResourceManager.GetString("TwoDigits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown state &apos;{0}&apos;.
        /// </summary>
        public static string UnknownState {
            get {
                return ResourceManager.GetString("UnknownState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while retrieving job. To continue, say VCONFIRM.
        /// </summary>
        public static string Workflow_ErrorRetrievingJob {
            get {
                return ResourceManager.GetString("Workflow_ErrorRetrievingJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job?.
        /// </summary>
        public static string Workflow_Job {
            get {
                return ResourceManager.GetString("Workflow_Job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job finished. To continue, say VCONFIRM.
        /// </summary>
        public static string Workflow_JobFinished {
            get {
                return ResourceManager.GetString("Workflow_JobFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job finished with skipped questions. To complete it, say no more . To continue, say VCONFIRM.
        /// </summary>
        public static string Workflow_JobFinishedWithSkippedQuestions {
            get {
                return ResourceManager.GetString("Workflow_JobFinishedWithSkippedQuestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job {0} not found.
        /// </summary>
        public static string Workflow_JobNotFound_Voice {
            get {
                return ResourceManager.GetString("Workflow_JobNotFound_Voice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leaving job.
        /// </summary>
        public static string Workflow_LeavingJob {
            get {
                return ResourceManager.GetString("Workflow_LeavingJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator {0} not found..
        /// </summary>
        public static string Workflow_OperatorNotFound {
            get {
                return ResourceManager.GetString("Workflow_OperatorNotFound", resourceCulture);
            }
        }
    }
}
