//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Honeywell.GWS.Connector.Library.Workflows.Checklist.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Honeywell.GWS.Connector.Library.Workflows.Checklist.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [{0}] Error setting answer for question &apos;{1}&apos;. Response was &apos;{2}&apos; ({3}): {4}.
        /// </summary>
        public static string Behavior_ErrorSettingAnswer {
            get {
                return ResourceManager.GetString("Behavior_ErrorSettingAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [{0}] Checklist not found.
        /// </summary>
        public static string Behavior_NotFound {
            get {
                return ResourceManager.GetString("Behavior_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [{0}] Question &apos;{1}&apos; not found.
        /// </summary>
        public static string Behavior_QuestionNotFound {
            get {
                return ResourceManager.GetString("Behavior_QuestionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [{0}] Checklist has questions with same code.
        /// </summary>
        public static string Behavior_RepeatedQuestions {
            get {
                return ResourceManager.GetString("Behavior_RepeatedQuestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [{0}] Retrieve: Unexpected Response &apos;{1}&apos;.
        /// </summary>
        public static string Checklist_Null {
            get {
                return ResourceManager.GetString("Checklist_Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid type &apos;{0}&apos;.
        /// </summary>
        public static string DataSetParser_InvalidType {
            get {
                return ResourceManager.GetString("DataSetParser_InvalidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Property &apos;{0}&apos; is mandatory.
        /// </summary>
        public static string DataSetParser_PropertyEmpty {
            get {
                return ResourceManager.GetString("DataSetParser_PropertyEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [{0}] Date Format in question &apos;{1}&apos; is not valid: &apos;{2}&apos; - {3}.
        /// </summary>
        public static string Date_InvalidFormat {
            get {
                return ResourceManager.GetString("Date_InvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The database was not accessible during initialization ({0}): {1}.
        /// </summary>
        public static string Error_DBNotAccessible {
            get {
                return ResourceManager.GetString("Error_DBNotAccessible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error updating checklist &apos;{0}&apos;: {1}.
        /// </summary>
        public static string Error_UpdateChecklist {
            get {
                return ResourceManager.GetString("Error_UpdateChecklist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a File Format is mandatory.
        /// </summary>
        public static string FileFormatEmpty {
            get {
                return ResourceManager.GetString("FileFormatEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [{0}] GetOperator: Unexpected Response &apos;{1}&apos;.
        /// </summary>
        public static string GetOperator_Null {
            get {
                return ResourceManager.GetString("GetOperator_Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Failed to parse: {0}.
        /// </summary>
        public static string JsonParser_FailedToParse {
            get {
                return ResourceManager.GetString("JsonParser_FailedToParse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid type &apos;{0}&apos;.
        /// </summary>
        public static string JsonParser_InvalidType {
            get {
                return ResourceManager.GetString("JsonParser_InvalidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [{0}] Operator &apos;{1}&apos; not found.
        /// </summary>
        public static string ServerConnection_OperatorNotFound {
            get {
                return ResourceManager.GetString("ServerConnection_OperatorNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Server is mandatory.
        /// </summary>
        public static string ServerEmpty {
            get {
                return ResourceManager.GetString("ServerEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unexpected response code: {0}.
        /// </summary>
        public static string StatusCodeDefault {
            get {
                return ResourceManager.GetString("StatusCodeDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [{0}] Time Format in question &apos;{1}&apos; is not valid: &apos;{2}&apos; - {3}.
        /// </summary>
        public static string Time_InvalidFormat {
            get {
                return ResourceManager.GetString("Time_InvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [{0}] Job not found.
        /// </summary>
        public static string Workflow_JobNotFound {
            get {
                return ResourceManager.GetString("Workflow_JobNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [{0}] Select Options not found.
        /// </summary>
        public static string Workflow_SelectOptionsNotFound {
            get {
                return ResourceManager.GetString("Workflow_SelectOptionsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [{0}] Unknown question type &apos;{1}&apos;.
        /// </summary>
        public static string Workflow_UnknownQuestionType {
            get {
                return ResourceManager.GetString("Workflow_UnknownQuestionType", resourceCulture);
            }
        }
    }
}
