//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Honeywell.GWS.Connector.Library.Workflows.Checklist.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources___Copy {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources___Copy() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Honeywell.GWS.Connector.Library.Workflows.Checklist.Properties.Resources - Copy", typeof(Resources___Copy).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] Error setting answer for question &apos;{1}&apos;. Response was &apos;{2}&apos; ({3}): {4}.
        /// </summary>
        public static string Behavior_ErrorSettingAnswer {
            get {
                return ResourceManager.GetString("Behavior_ErrorSettingAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] Checklist not found.
        /// </summary>
        public static string Behavior_NotFound {
            get {
                return ResourceManager.GetString("Behavior_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] Question &apos;{1}&apos; not found.
        /// </summary>
        public static string Behavior_QuestionNotFound {
            get {
                return ResourceManager.GetString("Behavior_QuestionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] Checklist has questions with same code.
        /// </summary>
        public static string Behavior_RepeatedQuestions {
            get {
                return ResourceManager.GetString("Behavior_RepeatedQuestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] Retrieve: Unexpected Response &apos;{1}&apos;.
        /// </summary>
        public static string Checklist_Null {
            get {
                return ResourceManager.GetString("Checklist_Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid type &apos;{0}&apos;.
        /// </summary>
        public static string DataSetParser_InvalidType {
            get {
                return ResourceManager.GetString("DataSetParser_InvalidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &apos;{0}&apos; is mandatory.
        /// </summary>
        public static string DataSetParser_PropertyEmpty {
            get {
                return ResourceManager.GetString("DataSetParser_PropertyEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] Date Format in question &apos;{1}&apos; is not valid: &apos;{2}&apos; - {3}.
        /// </summary>
        public static string Date_InvalidFormat {
            get {
                return ResourceManager.GetString("Date_InvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The database was not accessible during initialization ({0}): {1}.
        /// </summary>
        public static string Error_DBNotAccessible {
            get {
                return ResourceManager.GetString("Error_DBNotAccessible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error updating checklist &apos;{0}&apos;: {1}.
        /// </summary>
        public static string Error_UpdateChecklist {
            get {
                return ResourceManager.GetString("Error_UpdateChecklist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Format is mandatory.
        /// </summary>
        public static string FileFormatEmpty {
            get {
                return ResourceManager.GetString("FileFormatEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] GetOperator: Unexpected Response &apos;{1}&apos;.
        /// </summary>
        public static string GetOperator_Null {
            get {
                return ResourceManager.GetString("GetOperator_Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to parse: {0}.
        /// </summary>
        public static string JsonParser_FailedToParse {
            get {
                return ResourceManager.GetString("JsonParser_FailedToParse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid type &apos;{0}&apos;.
        /// </summary>
        public static string JsonParser_InvalidType {
            get {
                return ResourceManager.GetString("JsonParser_InvalidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] Operator &apos;{1}&apos; not found.
        /// </summary>
        public static string ServerConnection_OperatorNotFound {
            get {
                return ResourceManager.GetString("ServerConnection_OperatorNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server is mandatory.
        /// </summary>
        public static string ServerEmpty {
            get {
                return ResourceManager.GetString("ServerEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected response code: {0}.
        /// </summary>
        public static string StatusCodeDefault {
            get {
                return ResourceManager.GetString("StatusCodeDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] Time Format in question &apos;{1}&apos; is not valid: &apos;{2}&apos; - {3}.
        /// </summary>
        public static string Time_InvalidFormat {
            get {
                return ResourceManager.GetString("Time_InvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] Job not found.
        /// </summary>
        public static string Workflow_JobNotFound {
            get {
                return ResourceManager.GetString("Workflow_JobNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] Select Options not found.
        /// </summary>
        public static string Workflow_SelectOptionsNotFound {
            get {
                return ResourceManager.GetString("Workflow_SelectOptionsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] Unknown question type &apos;{1}&apos;.
        /// </summary>
        public static string Workflow_UnknownQuestionType {
            get {
                return ResourceManager.GetString("Workflow_UnknownQuestionType", resourceCulture);
            }
        }
    }
}
