//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Honeywell.GWS.Connector.Library.Workflows.Picking.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DialogResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DialogResources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Honeywell.GWS.Connector.Library.Workflows.Picking.Properties.DialogResources", typeof(DialogResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a , {0} containers.
        /// </summary>
        public static string BeginPickingOrder_ContainersCount {
            get {
                return ResourceManager.GetString("BeginPickingOrder_ContainersCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a , in {0}.
        /// </summary>
        public static string BeginPickingOrder_ContainerType {
            get {
                return ResourceManager.GetString("BeginPickingOrder_ContainerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Order {0}.
        /// </summary>
        public static string BeginPickingOrder_Order {
            get {
                return ResourceManager.GetString("BeginPickingOrder_Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Break reason?.
        /// </summary>
        public static string Break_ConfirmReason {
            get {
                return ResourceManager.GetString("Break_ConfirmReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a At break. To resume work, say VCONFIRM.
        /// </summary>
        public static string Break_Resume {
            get {
                return ResourceManager.GetString("Break_Resume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An error ocurred.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You can&apos;t access at this time: &apos;{0}&apos;. Say VCONFIRM or VSIGNOFF..
        /// </summary>
        public static string Error_Authentication {
            get {
                return ResourceManager.GetString("Error_Authentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error accessing: no response received from the server.
        /// </summary>
        public static string Error_ConnectMissingServerResponse {
            get {
                return ResourceManager.GetString("Error_ConnectMissingServerResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Incorrect.
        /// </summary>
        public static string Error_Incorrect {
            get {
                return ResourceManager.GetString("Error_Incorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unknown reason.
        /// </summary>
        public static string Error_UnknownReason {
            get {
                return ResourceManager.GetString("Error_UnknownReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No work assigned. To try again, say VCONFIRM.
        /// </summary>
        public static string GetWork_NotWork {
            get {
                return ResourceManager.GetString("GetWork_NotWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Breakage.
        /// </summary>
        public static string LowerQuantityMenu_Breakage {
            get {
                return ResourceManager.GetString("LowerQuantityMenu_Breakage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancel.
        /// </summary>
        public static string LowerQuantityMenu_Cancel {
            get {
                return ResourceManager.GetString("LowerQuantityMenu_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Complete.
        /// </summary>
        public static string LowerQuantityMenu_Complete {
            get {
                return ResourceManager.GetString("LowerQuantityMenu_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Continue.
        /// </summary>
        public static string LowerQuantityMenu_Continue {
            get {
                return ResourceManager.GetString("LowerQuantityMenu_Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dock.
        /// </summary>
        public static string LowerQuantityMenu_Dock {
            get {
                return ResourceManager.GetString("LowerQuantityMenu_Dock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Empty.
        /// </summary>
        public static string LowerQuantityMenu_Empty {
            get {
                return ResourceManager.GetString("LowerQuantityMenu_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aisle {0}.
        /// </summary>
        public static string PickingLine_Aisle {
            get {
                return ResourceManager.GetString("PickingLine_Aisle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contains packaging?.
        /// </summary>
        public static string PickingLine_AskPackage {
            get {
                return ResourceManager.GetString("PickingLine_AskPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Breakage quantity?.
        /// </summary>
        public static string PickingLine_BreakageQuantity {
            get {
                return ResourceManager.GetString("PickingLine_BreakageQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Check digit?.
        /// </summary>
        public static string PickingLine_CD {
            get {
                return ResourceManager.GetString("PickingLine_CD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a  , correct?.
        /// </summary>
        public static string PickingLine_Confirm {
            get {
                return ResourceManager.GetString("PickingLine_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Batch {0}?.
        /// </summary>
        public static string PickingLine_ConfirmBatch {
            get {
                return ResourceManager.GetString("PickingLine_ConfirmBatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There are {0} lines remaining.
        /// </summary>
        public static string PickingLine_HowMuchMore {
            get {
                return ResourceManager.GetString("PickingLine_HowMuchMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a . Is this a short?.
        /// </summary>
        public static string PickingLine_IsShort {
            get {
                return ResourceManager.GetString("PickingLine_IsShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reason code?.
        /// </summary>
        public static string PickingLine_LowerQuantityReason {
            get {
                return ResourceManager.GetString("PickingLine_LowerQuantityReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The maximum quantity allowed per pick is.
        /// </summary>
        public static string PickingLine_MaxQuantityAllowed {
            get {
                return ResourceManager.GetString("PickingLine_MaxQuantityAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The weight is more than allowed.
        /// </summary>
        public static string PickingLine_MaxWeightAllowed {
            get {
                return ResourceManager.GetString("PickingLine_MaxWeightAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The weight is less than allowed.
        /// </summary>
        public static string PickingLine_MinWeightAllowed {
            get {
                return ResourceManager.GetString("PickingLine_MinWeightAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Information not available.
        /// </summary>
        public static string PickingLine_MissingData {
            get {
                return ResourceManager.GetString("PickingLine_MissingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Not allowed.
        /// </summary>
        public static string PickingLine_NotAllowed {
            get {
                return ResourceManager.GetString("PickingLine_NotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Remain.
        /// </summary>
        public static string PickingLine_PendingQuantity {
            get {
                return ResourceManager.GetString("PickingLine_PendingQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a , you said .
        /// </summary>
        public static string PickingLine_PickedQuantity {
            get {
                return ResourceManager.GetString("PickingLine_PickedQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Quantity greater than requested.
        /// </summary>
        public static string PickingLine_QuantityGreater {
            get {
                return ResourceManager.GetString("PickingLine_QuantityGreater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Quantity in location.
        /// </summary>
        public static string PickingLine_QuantityInLocation {
            get {
                return ResourceManager.GetString("PickingLine_QuantityInLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Asked for .
        /// </summary>
        public static string PickingLine_RequiredQuantity {
            get {
                return ResourceManager.GetString("PickingLine_RequiredQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select batch.
        /// </summary>
        public static string PickingLine_SelectBatch {
            get {
                return ResourceManager.GetString("PickingLine_SelectBatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Slot {0}.
        /// </summary>
        public static string PickingLine_Slot {
            get {
                return ResourceManager.GetString("PickingLine_Slot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} units.
        /// </summary>
        public static string PickingLine_Units {
            get {
                return ResourceManager.GetString("PickingLine_Units", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Weight?.
        /// </summary>
        public static string PickingLine_Weight {
            get {
                return ResourceManager.GetString("PickingLine_Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Specify destination.
        /// </summary>
        public static string PlaceInDock_Destination {
            get {
                return ResourceManager.GetString("PlaceInDock_Destination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dock {0}.
        /// </summary>
        public static string PlaceInDock_Dock {
            get {
                return ResourceManager.GetString("PlaceInDock_Dock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pallet location.
        /// </summary>
        public static string PlaceInDock_Location {
            get {
                return ResourceManager.GetString("PlaceInDock_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pallet placed.
        /// </summary>
        public static string PlaceInDock_PalletPlaced {
            get {
                return ResourceManager.GetString("PlaceInDock_PalletPlaced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Place in dock.
        /// </summary>
        public static string PlaceInDock_PlaceInDock {
            get {
                return ResourceManager.GetString("PlaceInDock_PlaceInDock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Completed.
        /// </summary>
        public static string PrintLabels_Completed {
            get {
                return ResourceManager.GetString("PrintLabels_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a , to print, say VCONFIRM.
        /// </summary>
        public static string PrintLabels_Confirm {
            get {
                return ResourceManager.GetString("PrintLabels_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Printer?.
        /// </summary>
        public static string PrintLabels_ConfirmPrinter {
            get {
                return ResourceManager.GetString("PrintLabels_ConfirmPrinter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correct printing?.
        /// </summary>
        public static string PrintLabels_ConfirmResult {
            get {
                return ResourceManager.GetString("PrintLabels_ConfirmResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a How many labels?.
        /// </summary>
        public static string PrintLabels_Labels {
            get {
                return ResourceManager.GetString("PrintLabels_Labels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Printer.
        /// </summary>
        public static string PrintLabels_Printer {
            get {
                return ResourceManager.GetString("PrintLabels_Printer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Printers not available.
        /// </summary>
        public static string PrintLabels_PrintersNotAvailable {
            get {
                return ResourceManager.GetString("PrintLabels_PrintersNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Retrying....
        /// </summary>
        public static string PrintLabels_Retrying {
            get {
                return ResourceManager.GetString("PrintLabels_Retrying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a unknown.
        /// </summary>
        public static string PrintLabels_Unknown {
            get {
                return ResourceManager.GetString("PrintLabels_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unknown printer.
        /// </summary>
        public static string PrintLabels_UnknownPrinter {
            get {
                return ResourceManager.GetString("PrintLabels_UnknownPrinter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Validate labels.
        /// </summary>
        public static string ValidatePrinting_Confirm {
            get {
                return ResourceManager.GetString("ValidatePrinting_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Validate label.
        /// </summary>
        public static string ValidatePrinting_ConfirmLabel {
            get {
                return ResourceManager.GetString("ValidatePrinting_ConfirmLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a , remain .
        /// </summary>
        public static string ValidatePrinting_Pendings {
            get {
                return ResourceManager.GetString("ValidatePrinting_Pendings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Validation completed.
        /// </summary>
        public static string ValidatePrinting_ValidationCompleted {
            get {
                return ResourceManager.GetString("ValidatePrinting_ValidationCompleted", resourceCulture);
            }
        }
    }
}
